version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: almoxarifado-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: almoxarifado
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - almoxarifado-network

  # Aplicação
  app:
    build: .
    container_name: almoxarifado-app
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/almoxarifado?authSource=admin
      JWT_SECRET: sua_chave_secreta_muito_segura_aqui
      PORT: 3001
    ports:
      - "3001:3001"
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - almoxarifado-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules

  # MongoDB Express (Interface web para MongoDB)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: almoxarifado-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - almoxarifado-network

volumes:
  mongodb_data:

networks:
  almoxarifado-network:
    driver: bridge 