#!/bin/bash

echo "🔧 Corrigindo problema do JWT_SECRET na VPS..."

# Conectar na VPS e executar os comandos
echo "📋 Comandos para executar na VPS:"
echo ""
echo "1. Acessar a pasta do projeto:"
echo "   cd /var/www/controledeinsumos"
echo ""
echo "2. Verificar se o arquivo .env existe:"
echo "   ls -la .env*"
echo ""
echo "3. Se não existir, criar o arquivo .env:"
echo "   cp env.example .env"
echo ""
echo "4. Editar o arquivo .env e adicionar:"
echo "   JWT_SECRET=sua_chave_secreta_muito_segura_aqui_2024"
echo "   DB_HOST=localhost"
echo "   DB_USER=insumos_user"
echo "   DB_PASS=sua_senha_do_banco"
echo "   DB_NAME=insumos_db"
echo "   DB_PORT=3306"
echo "   PORT=3001"
echo ""
echo "5. Reiniciar o PM2:"
echo "   pm2 restart all"
echo ""
echo "6. Verificar logs:"
echo "   pm2 logs --lines 20"
echo ""

echo "🎯 Alternativa rápida - Execute na VPS:"
echo ""
echo "cd /var/www/controledeinsumos && echo 'JWT_SECRET=sua_chave_secreta_muito_segura_aqui_2024' >> .env && pm2 restart all"
echo "" 